server:
  port: 8091

spring:
  application:
    name: Personas
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: /h2
  profiles:
    include: null

adapters:
  r2dbc:
    host: localhost
    port: 5435
    database: usuarios
    schema: public
    username: postgres
    password: postgres

routers:
  paths:
    users: /api/v1/personas